// <auto-generated />
namespace Fixie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PendingChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PendingChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201301180818276_PendingChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
