// <auto-generated />
namespace Fixie.Api.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BasicUserInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasicUserInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201301171728282_BasicUserInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
